package Expense;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class ExpenseJDBCService implements ExpenseService {

    @Override
    public Expense addExpense(Long itemID) {
        Expense expense = null;
        try(Connection connection = db.getConnection()) {
            PreparedStatement statement = connection.prepareStatement(
                    "INSERT INTO Expense (user_id, amount, category, date) Values (?, ?, ?, ?)");
            statement.setLong(1, expense.getUserId());
            statement.setInt(2, expense.getAmount());
            statement.setString(3, expense.getCategory());
            statement.setDate(4, expense.getDate());
            statement.executeUpdate();

            //Retrieve Autogenerated ID
            ResultSet generatedKeys = statement.getGeneratedKeys();
            if (generatedKeys.next()) {
                expense.setItemId(generatedKeys.getLong(1));
            }
        }catch (SQLException e){
                throw new RuntimeException("Error saving account", e);
        }
            return expense;
    }

    @Override
    public Expense viewExpense(Expense expense) {
        return null;
    }

    @Override
    public Expense deleteExpense(Expense expense) {
        return null;
    }

    @Override
    public Expense filterExpense(Expense expense) {
        return null;
    }

    @Override
    public Expense expenseSummary(Expense expense) {
        return null;
    }
}
